# Generated by Django 3.0.8 on 2020-07-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytunes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mytunes',
            new_name='Album',
        ),
    ]
